app:
  jwtSecret: fang
  logPath: ./logs/gin.log
server:
  runMode: debug
  httpPort: 8000
redis:
  host: 192.168.137.133:6379
  password:
  maxIdle: 30
  maxActive: 30
  idleTimeout: 200

datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  url: jdbc:mysql://localhost:3306/db_example
  username: springuser
  password: 123456
